# Generated by Django 4.1.7 on 2023-02-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganDonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('age', models.PositiveIntegerField()),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('temperature', models.FloatField()),
                ('health', models.CharField(choices=[('healthy', 'Healthy'), ('sick', 'Sick')], max_length=10)),
                ('diabetes', models.BooleanField(default=False)),
                ('drug_addict', models.BooleanField(default=False)),
                ('smoker', models.BooleanField(default=False)),
                ('after_heart_attack', models.BooleanField(default=False)),
                ('alcoholic', models.BooleanField(default=False)),
                ('aids', models.BooleanField(default=False)),
                ('cancer', models.BooleanField(default=False)),
                ('alcohol_in_process', models.BooleanField(default=False)),
                ('drugs_in_process', models.BooleanField(default=False)),
                ('mental_illness', models.BooleanField(default=False)),
                ('ethnicity', models.CharField(choices=[('White', 'White'), ('Black', 'Black'), ('Hispanic', 'Hispanic'), ('Asian', 'Asian'), ('Other', 'Other')], max_length=10)),
                ('skin_color', models.CharField(choices=[('Light', 'Light'), ('Medium', 'Medium'), ('Dark', 'Dark')], max_length=10)),
            ],
        ),
    ]
