# Generated by Django 4.1.7 on 2023-02-28 17:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('international_organ_players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='organdonor',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='organrecipient',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='OrganPossessed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquisition_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organs', to='international_organ_players.clinic')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organs', to='international_organ_players.organdonor')),
                ('organ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='existings', to='international_organ_players.organdata')),
            ],
        ),
    ]
