# Generated by Django 4.1.7 on 2023-02-25 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_organ_players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganData',
            fields=[
                ('organ', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('operation_time', models.PositiveIntegerField()),
                ('max_delivery_time', models.PositiveIntegerField()),
                ('difficulty_of_operation', models.CharField(default='easy', max_length=32)),
                ('min_price', models.PositiveIntegerField()),
                ('max_price', models.PositiveIntegerField()),
                ('difficulty_of_transportation', models.CharField(default='easy', max_length=64)),
                ('people_to_transport', models.PositiveIntegerField()),
                ('nurses_on_the_operation', models.PositiveIntegerField()),
                ('anesthesiologists_on_the_operation', models.PositiveIntegerField()),
                ('surgeons_on_the_operation', models.PositiveIntegerField()),
            ],
        ),
    ]
