# Generated by Django 4.1.7 on 2023-02-25 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('international_organ_players', '0002_organdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('maximum_waiting_time', models.PositiveIntegerField()),
                ('skin_color', models.CharField(choices=[('Light', 'Light'), ('Medium', 'Medium'), ('Dark', 'Dark')], max_length=10)),
                ('price', models.PositiveIntegerField()),
                ('location', models.CharField(default='Wroclaw', max_length=30)),
                ('organ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='international_organ_players.organdata')),
            ],
        ),
    ]
