# Generated by Django 4.1.7 on 2023-02-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_organ_players', '0003_remove_clinic_organ_fridge_clinic_organ_storage_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organdata',
            name='does_blood_type_matter',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organdata',
            name='does_skin_color_matter',
            field=models.BooleanField(default=False),
        ),
    ]
