# Generated by Django 4.1.7 on 2023-03-02 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('international_organ_players', '0004_organdata_does_blood_type_matter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinics', to='international_organ_players.player'),
        ),
    ]
