# Generated by Django 2.2.24 on 2023-02-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_organ_players', '0004_auto_20230226_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organdata',
            name='min_price',
            field=models.CharField(max_length=32),
        ),
    ]
