# Generated by Django 4.1.7 on 2023-03-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_organ_players', '0005_alter_clinic_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='bitcoins',
            field=models.DecimalField(decimal_places=6, default=0.5, max_digits=20),
        ),
        migrations.AddField(
            model_name='player',
            name='dollars',
            field=models.BigIntegerField(default=100000),
        ),
    ]
