# Generated by Django 4.1.7 on 2023-02-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_organ_players', '0006_auto_20230226_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organdonor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='organrecipient',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Clinic',
        ),
        migrations.DeleteModel(
            name='MedicalStaff',
        ),
        migrations.DeleteModel(
            name='TechnicalStaff',
        ),
    ]
