# Generated by Django 4.1.7 on 2023-02-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_organ_players', '0007_alter_organdonor_id_alter_organrecipient_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(choices=[('nurse', 'Nurse'), ('surgeon', 'Surgeon'), ('anesthesiologist', 'Anesthesiologist')], max_length=20)),
                ('username', models.CharField(max_length=15)),
                ('surname', models.CharField(max_length=15)),
                ('age', models.PositiveSmallIntegerField()),
                ('skill', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('cost_per_hour', models.PositiveIntegerField()),
                ('maximum_time_of_shift', models.PositiveSmallIntegerField()),
                ('number_of_vacation_days', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(choices=[('electrician', 'Electrician'), ('cleaner', 'Cleaner'), ('secretary', 'Secretary'), ('gangster', 'Gangster'), ('gravedigger', 'Gravedigger'), ('driver', 'Driver')], max_length=20)),
                ('username', models.CharField(max_length=15)),
                ('surname', models.CharField(max_length=15)),
                ('age', models.PositiveSmallIntegerField()),
                ('skill', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('cost_per_hour', models.PositiveIntegerField()),
                ('maximum_time_of_shift', models.PositiveSmallIntegerField()),
                ('number_of_vacation_days', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('appearance_scale', models.PositiveSmallIntegerField(default=1, help_text='Scale from 1 to 20')),
                ('vehicle', models.CharField(default='bicycle', max_length=50)),
                ('garage', models.BooleanField(default=False)),
                ('helipad', models.BooleanField(default=False)),
                ('runway', models.BooleanField(default=False)),
                ('hangar', models.BooleanField(default=False)),
                ('mortuary_capacity', models.IntegerField(default=0, help_text='Capacity for number of persons')),
                ('organ_fridge', models.BooleanField(default=False)),
                ('rating', models.IntegerField(default=100, help_text='Rating scale from 1 to 100')),
                ('medical_personnel', models.ManyToManyField(related_name='clinics', to='international_organ_players.medicalstaff')),
                ('technical_staff', models.ManyToManyField(related_name='clinics', to='international_organ_players.technicalstaff')),
            ],
        ),
    ]
