# Generated by Django 4.1.7 on 2023-02-26 12:37

from django.db import migrations, models
import international_organ_players.models


class Migration(migrations.Migration):

    dependencies = [
        ('international_organ_players', '0008_medicalstaff_technicalstaff_clinic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_storage_area', models.CharField(max_length=20, verbose_name=international_organ_players.models.VehicleStorageArea)),
                ('vehicle', models.CharField(max_length=20)),
                ('speed', models.PositiveSmallIntegerField(verbose_name='in km/h')),
                ('purchase_price', models.PositiveIntegerField()),
                ('maintenance_price', models.PositiveIntegerField(help_text='per day')),
                ('price_per_km', models.PositiveIntegerField()),
                ('minimum_distance', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleStorageArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=20)),
                ('maximum_capacity', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='clinic',
            name='vehicle',
            field=models.ManyToManyField(to='international_organ_players.vehicle'),
        ),
    ]
