# Generated by Django 4.1.7 on 2023-02-26 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('international_organ_players', '0009_vehicle_vehiclestoragearea_remove_clinic_vehicle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_storage_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='international_organ_players.vehiclestoragearea'),
        ),
    ]
