# Generated by Django 4.1.7 on 2023-02-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_organ_players', '0010_alter_vehicle_vehicle_storage_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='technical_staff',
            field=models.ManyToManyField(null=True, related_name='clinics', to='international_organ_players.technicalstaff'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='speed',
            field=models.PositiveSmallIntegerField(help_text='in km/h'),
        ),
    ]
