# Generated by Django 4.1.7 on 2023-02-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_organ_players', '0011_alter_clinic_technical_staff_alter_vehicle_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='technical_staff',
            field=models.ManyToManyField(blank=True, related_name='clinics', to='international_organ_players.technicalstaff'),
        ),
    ]
