# Generated by Django 4.1.7 on 2023-02-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_organ_players', '0012_alter_clinic_technical_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganStorageArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_name', models.CharField(max_length=20)),
                ('organ_depot_level', models.PositiveIntegerField(verbose_name=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('capacity', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], max_length=2)),
                ('multiplier_for_organ_suitability', models.FloatField(default=1, help_text='type = float')),
                ('mobile', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='clinic',
            name='medical_personnel',
            field=models.ManyToManyField(blank=True, related_name='clinics', to='international_organ_players.medicalstaff'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='vehicle',
            field=models.ManyToManyField(blank=True, related_name='clinics', to='international_organ_players.vehicle'),
        ),
    ]
