# Generated by Django 4.1.7 on 2023-02-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_organ_players', '0013_organstoragearea_alter_clinic_medical_personnel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalstaff',
            old_name='username',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='organstoragearea',
            old_name='mobile',
            new_name='is_mobile',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='appearance_scale',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='garage',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='hangar',
        ),
        migrations.RemoveField(
            model_name='medicalstaff',
            name='maximum_time_of_shift',
        ),
        migrations.RemoveField(
            model_name='organdata',
            name='difficulty_of_transportation',
        ),
        migrations.RemoveField(
            model_name='organdata',
            name='max_delivery_time',
        ),
        migrations.RemoveField(
            model_name='technicalstaff',
            name='maximum_time_of_shift',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_storage_area',
        ),
        migrations.RemoveField(
            model_name='vehiclestoragearea',
            name='maximum_capacity',
        ),
        migrations.RemoveField(
            model_name='vehiclestoragearea',
            name='place_name',
        ),
        migrations.AddField(
            model_name='clinic',
            name='apperance',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], default=1, help_text='Scale from 1 to 20'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='vehicle_storages',
            field=models.ManyToManyField(blank=True, related_name='clinics', to='international_organ_players.vehiclestoragearea'),
        ),
        migrations.AddField(
            model_name='organdata',
            name='difficulty_of_depot',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organdata',
            name='difficulty_of_transport',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organdata',
            name='max_alive_time',
            field=models.PositiveIntegerField(default=240, help_text='in minutes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technicalstaff',
            name='max_time_per_shift',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], default=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='level_of_transportability',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='storage_level',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiclestoragearea',
            name='capacity',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiclestoragearea',
            name='storage_level',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiclestoragearea',
            name='storage_name',
            field=models.CharField(default='storage', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clinic',
            name='mortuary_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='rating',
            field=models.IntegerField(default=90, help_text='Rating scale from 1 to 100'),
        ),
        migrations.AlterField(
            model_name='medicalstaff',
            name='skill',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)]),
        ),
        migrations.AlterField(
            model_name='organdata',
            name='anesthesiologists_on_the_operation',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.AlterField(
            model_name='organdata',
            name='difficulty_of_operation',
            field=models.CharField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], max_length=2),
        ),
        migrations.AlterField(
            model_name='organdata',
            name='max_price',
            field=models.PositiveIntegerField(help_text='in Dollars'),
        ),
        migrations.AlterField(
            model_name='organdata',
            name='min_price',
            field=models.PositiveIntegerField(help_text='in Dollars'),
        ),
        migrations.AlterField(
            model_name='organdata',
            name='nurses_on_the_operation',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.AlterField(
            model_name='organdata',
            name='people_to_transport',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.AlterField(
            model_name='organdata',
            name='surgeons_on_the_operation',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.AlterField(
            model_name='organrecipient',
            name='price',
            field=models.PositiveIntegerField(help_text='in Dollars'),
        ),
        migrations.AlterField(
            model_name='organstoragearea',
            name='capacity',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)]),
        ),
        migrations.AlterField(
            model_name='organstoragearea',
            name='organ_depot_level',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.AlterField(
            model_name='technicalstaff',
            name='skill',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='minimum_distance',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='price_per_km',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
