# Generated by Django 4.1.7 on 2023-02-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_organ_players', '0015_medicalstaff_max_time_per_shift_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organstoragearea',
            name='price',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiclestoragearea',
            name='price',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
    ]
