# Generated by Django 4.1.7 on 2023-02-26 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('international_organ_players', '0016_organstoragearea_price_vehiclestoragearea_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_booster', models.CharField(max_length=20)),
                ('how_long_it_takes', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_equipment', models.CharField(max_length=20)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=20)),
                ('multiplier_for_operation_skills', models.FloatField()),
                ('change_over_time', models.FloatField(help_text='per hour')),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id_of_procedure', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.PositiveSmallIntegerField(help_text='ID of avatar')),
                ('nickname', models.CharField(max_length=30)),
                ('stamina', models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('alcohol', models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('temperature', models.FloatField(default=36.6)),
                ('sight', models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('hunger', models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('mental_state', models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('dementia', models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('time_per_shift', models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('knowledge', models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('intelligence', models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('nationality', models.CharField(max_length=30)),
                ('drugs', models.ManyToManyField(blank=True, related_name='players', to='international_organ_players.booster')),
                ('equipment', models.ManyToManyField(blank=True, related_name='players', to='international_organ_players.equipment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='enables_the_procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='international_organ_players.procedure'),
        ),
        migrations.AddField(
            model_name='booster',
            name='which_improves',
            field=models.ManyToManyField(blank=True, related_name='boosters', to='international_organ_players.playerattributes'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='equipment',
            field=models.ManyToManyField(blank=True, related_name='clinics', to='international_organ_players.equipment'),
        ),
        migrations.AddField(
            model_name='organdata',
            name='procedures',
            field=models.ManyToManyField(related_name='organs', to='international_organ_players.procedure'),
        ),
    ]
