# Generated by Django 4.1.7 on 2023-02-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_organ_players', '0017_booster_equipment_playerattributes_procedure_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booster',
            name='which_worsens',
            field=models.ManyToManyField(blank=True, related_name='booster_worses', to='international_organ_players.playerattributes'),
        ),
        migrations.AlterField(
            model_name='booster',
            name='which_improves',
            field=models.ManyToManyField(blank=True, related_name='booster_improves', to='international_organ_players.playerattributes'),
        ),
    ]
