# Generated by Django 4.1.7 on 2023-02-26 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('international_organ_players', '0018_booster_which_worsens_alter_booster_which_improves'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='international_organ_players.player'),
            preserve_default=False,
        ),
    ]
